name: "Terraform Destroy"

on:
  workflow_dispatch: # Permite disparar manualmente pelo botão no GitHub

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.HW_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.HW_SECRET_KEY }}
      AWS_REGION: "la-south-2"
      AWS_EC2_METADATA_DISABLED: "true"
      TF_VAR_hw_ak: ${{ secrets.HW_ACCESS_KEY }}
      TF_VAR_hw_sk: ${{ secrets.HW_SECRET_KEY }}
      TF_VAR_hw_project_id: ${{ secrets.HW_PROJECT_ID }}

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7 # Mesma versão para evitar erro de SHA256

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./infra